services:
  - name: Front
    type: web
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    env:
      - key: NODE_ENV
        value: production
  - name: Server
    type: web
    buildCommand: npm install
    startCommand: node server.js
    env:
      - key: NODE_ENV
        value: production
